### ISSUE TITLE
0 profit listed for Polarized items

### ISSUE THREAD

**Issue by wffurr** [fuzzysteve/Eve-Blueprint-Calculator#3]
All polarized items, e.g. Polarized Torpedo Launcher: https://www.fuzzwork.co.uk/blueprint/?typeid=34294, show a 0 profit per run despite price - material - install not being 0 using the figures listed on the page.

**Comment by fuzzysteve** [comment]
bah. Side effect of polarised stuff being T2, but not having any invention to make them.

Sorted now, by checking for invention materials, as well as being T2.
